CREATE TABLE {1}_log (
	{1}_log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    field_name VARCHAR2(128) NOT NULL, -- 64 for MySQL, 128 for Oracle
    old_value VARCHAR2(32767) NULL,
    new_value VARCHAR2(32767) NULL,
    updated_by VARCHAR2(50) NOT NULL,
    updated_dts DATE NOT NULL,
    PRIMARY KEY ({1}_log_id)
)
    